package net.bogor.itu.entity.radius;

// Generated Mar 6, 2013 12:12:52 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nas generated by hbm2java
 */
@Entity
@Table(name = "nas", catalog = "radius")
public class Nas implements java.io.Serializable {

	private Integer id;
	private String nasname;
	private String shortname;
	private String type;
	private Integer ports;
	private String secret;
	private String community;
	private String description;
	private String password;
	private boolean ciscobwmode;

	public Nas() {
	}

	public Nas(String nasname, String secret, String password,
			boolean ciscobwmode) {
		this.nasname = nasname;
		this.secret = secret;
		this.password = password;
		this.ciscobwmode = ciscobwmode;
	}

	public Nas(String nasname, String shortname, String type, Integer ports,
			String secret, String community, String description,
			String password, boolean ciscobwmode) {
		this.nasname = nasname;
		this.shortname = shortname;
		this.type = type;
		this.ports = ports;
		this.secret = secret;
		this.community = community;
		this.description = description;
		this.password = password;
		this.ciscobwmode = ciscobwmode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nasname", nullable = false, length = 128)
	public String getNasname() {
		return this.nasname;
	}

	public void setNasname(String nasname) {
		this.nasname = nasname;
	}

	@Column(name = "shortname", length = 32)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ports")
	public Integer getPorts() {
		return this.ports;
	}

	public void setPorts(Integer ports) {
		this.ports = ports;
	}

	@Column(name = "secret", nullable = false, length = 60)
	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	@Column(name = "community", length = 50)
	public String getCommunity() {
		return this.community;
	}

	public void setCommunity(String community) {
		this.community = community;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "_password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "_ciscobwmode", nullable = false)
	public boolean isCiscobwmode() {
		return this.ciscobwmode;
	}

	public void setCiscobwmode(boolean ciscobwmode) {
		this.ciscobwmode = ciscobwmode;
	}

}
