package net.bogor.itu.entity.radius;

// Generated Mar 6, 2013 12:12:52 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Radgroupreply generated by hbm2java
 */
@Entity
@Table(name = "radgroupreply", catalog = "radius")
public class Radgroupreply implements java.io.Serializable {

	private Integer id;
	private String groupname;
	private String attribute;
	private String op;
	private String value;

	public Radgroupreply() {
	}

	public Radgroupreply(String groupname, String attribute, String op,
			String value) {
		this.groupname = groupname;
		this.attribute = attribute;
		this.op = op;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "groupname", nullable = false, length = 64)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "attribute", nullable = false, length = 64)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "op", nullable = false, length = 2)
	public String getOp() {
		return this.op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	@Column(name = "value", nullable = false, length = 253)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
