package net.bogor.itu.entity.radius;

// Generated Mar 6, 2013 12:12:52 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Radpostauth generated by hbm2java
 */
@Entity
@Table(name = "radpostauth", catalog = "radius")
public class Radpostauth implements java.io.Serializable {

	private Integer id;
	private String username;
	private String pass;
	private String reply;
	private Date authdate;

	public Radpostauth() {
	}

	public Radpostauth(String username, String pass, String reply, Date authdate) {
		this.username = username;
		this.pass = pass;
		this.reply = reply;
		this.authdate = authdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass", nullable = false, length = 64)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "reply", nullable = false, length = 32)
	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authdate", nullable = false, length = 19)
	public Date getAuthdate() {
		return this.authdate;
	}

	public void setAuthdate(Date authdate) {
		this.authdate = authdate;
	}

}
