package net.bogor.itu.entity.radius;

// Generated Mar 6, 2013 12:12:52 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Radusergroup generated by hbm2java
 */
@Entity
@Table(name = "radusergroup", catalog = "radius")
public class Radusergroup implements java.io.Serializable {

	private RadusergroupId id;

	public Radusergroup() {
	}

	public Radusergroup(RadusergroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 64)),
			@AttributeOverride(name = "groupname", column = @Column(name = "groupname", nullable = false, length = 64)),
			@AttributeOverride(name = "priority", column = @Column(name = "priority", nullable = false)) })
	public RadusergroupId getId() {
		return this.id;
	}

	public void setId(RadusergroupId id) {
		this.id = id;
	}

}
