package net.bogor.itu.entity.radius;

// Generated Mar 6, 2013 12:12:52 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RadusergroupId generated by hbm2java
 */
@Embeddable
public class RadusergroupId implements java.io.Serializable {

	private String username;
	private String groupname;
	private int priority;

	public RadusergroupId() {
	}

	public RadusergroupId(String username, String groupname, int priority) {
		this.username = username;
		this.groupname = groupname;
		this.priority = priority;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "groupname", nullable = false, length = 64)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RadusergroupId))
			return false;
		RadusergroupId castOther = (RadusergroupId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this
				.getUsername() != null && castOther.getUsername() != null && this
				.getUsername().equals(castOther.getUsername())))
				&& ((this.getGroupname() == castOther.getGroupname()) || (this
						.getGroupname() != null
						&& castOther.getGroupname() != null && this
						.getGroupname().equals(castOther.getGroupname())))
				&& (this.getPriority() == castOther.getPriority());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getGroupname() == null ? 0 : this.getGroupname().hashCode());
		result = 37 * result + this.getPriority();
		return result;
	}

}
